sudo: required
services:
  - docker

before_install:
  - docker build -t y8zhuang/test_build -f Dockerfile.dev .

script:
  - docker run -e CI=true y8zhuang/test_build npm help

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-example"
  env: "DockerExample-env"
  bucket_name: "elasticbeanstalk-sa-east-1-245943275219"
  bucket_path: "docker-example"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
